@{
    pd = 'PenDown'
    pu = 'PenUp'
    fd = 'Forward'
    down = 'PenDown'
    up = 'PenUp'
    l = 'Left'
    lt = 'Left'
    rt = 'Right'
    r = 'Right'
    xPos = 'xcor'
    yPos = 'ycor'
    LineTo = 'GoTo'
    SetPos = 'GoTo'
    SetPosition = 'GoTo'
    MoveTo = 'Teleport'
    Back = 'Backward'
    bk = 'Backward'
    ArcR = 'ArcRight'
    ArcL = 'ArcLeft'
    HLineBy = 'HorizontalLine'
    VLineBy = 'VerticalLine'
    FlowerStar = 'StarFlower'
    FlowerGolden = 'GoldenFlower'
}